const plugin = require('tailwindcss/plugin')

/** @type {import('tailwindcss').Config} */

module.exports = {
   theme: {
      extend: {
         _baseColors: {
            'base-black': 'var(--base-black)',
            'base-transparent': 'var(--base-transparent)',
            'base-white': 'var(--base-white)',
            'blue-100': 'var(--blue-100)',
            'blue-200': 'var(--blue-200)',
            'blue-25': 'var(--blue-25)',
            'blue-300': 'var(--blue-300)',
            'blue-400': 'var(--blue-400)',
            'blue-50': 'var(--blue-50)',
            'blue-500': 'var(--blue-500)',
            'blue-600': 'var(--blue-600)',
            'blue-700': 'var(--blue-700)',
            'blue-800': 'var(--blue-800)',
            'blue-900': 'var(--blue-900)',
            'blue-950': 'var(--blue-950)',
            'blue-dark-100': 'var(--blue-dark-100)',
            'blue-dark-200': 'var(--blue-dark-200)',
            'blue-dark-25': 'var(--blue-dark-25)',
            'blue-dark-300': 'var(--blue-dark-300)',
            'blue-dark-400': 'var(--blue-dark-400)',
            'blue-dark-50': 'var(--blue-dark-50)',
            'blue-dark-500': 'var(--blue-dark-500)',
            'blue-dark-600': 'var(--blue-dark-600)',
            'blue-dark-700': 'var(--blue-dark-700)',
            'blue-dark-800': 'var(--blue-dark-800)',
            'blue-dark-900': 'var(--blue-dark-900)',
            'blue-dark-950': 'var(--blue-dark-950)',
            'blue-light-100': 'var(--blue-light-100)',
            'blue-light-200': 'var(--blue-light-200)',
            'blue-light-25': 'var(--blue-light-25)',
            'blue-light-300': 'var(--blue-light-300)',
            'blue-light-400': 'var(--blue-light-400)',
            'blue-light-50': 'var(--blue-light-50)',
            'blue-light-500': 'var(--blue-light-500)',
            'blue-light-600': 'var(--blue-light-600)',
            'blue-light-700': 'var(--blue-light-700)',
            'blue-light-800': 'var(--blue-light-800)',
            'blue-light-900': 'var(--blue-light-900)',
            'blue-light-950': 'var(--blue-light-950)',
            'cyan-100': 'var(--cyan-100)',
            'cyan-200': 'var(--cyan-200)',
            'cyan-25': 'var(--cyan-25)',
            'cyan-300': 'var(--cyan-300)',
            'cyan-400': 'var(--cyan-400)',
            'cyan-50': 'var(--cyan-50)',
            'cyan-500': 'var(--cyan-500)',
            'cyan-600': 'var(--cyan-600)',
            'cyan-700': 'var(--cyan-700)',
            'cyan-800': 'var(--cyan-800)',
            'cyan-900': 'var(--cyan-900)',
            'cyan-950': 'var(--cyan-950)',
            'fuchsia-100': 'var(--fuchsia-100)',
            'fuchsia-200': 'var(--fuchsia-200)',
            'fuchsia-25': 'var(--fuchsia-25)',
            'fuchsia-300': 'var(--fuchsia-300)',
            'fuchsia-400': 'var(--fuchsia-400)',
            'fuchsia-50': 'var(--fuchsia-50)',
            'fuchsia-500': 'var(--fuchsia-500)',
            'fuchsia-600': 'var(--fuchsia-600)',
            'fuchsia-700': 'var(--fuchsia-700)',
            'fuchsia-800': 'var(--fuchsia-800)',
            'fuchsia-900': 'var(--fuchsia-900)',
            'fuchsia-950': 'var(--fuchsia-950)',
            'gray-blue-100': 'var(--gray-blue-100)',
            'gray-blue-200': 'var(--gray-blue-200)',
            'gray-blue-25': 'var(--gray-blue-25)',
            'gray-blue-300': 'var(--gray-blue-300)',
            'gray-blue-400': 'var(--gray-blue-400)',
            'gray-blue-50': 'var(--gray-blue-50)',
            'gray-blue-500': 'var(--gray-blue-500)',
            'gray-blue-600': 'var(--gray-blue-600)',
            'gray-blue-700': 'var(--gray-blue-700)',
            'gray-blue-800': 'var(--gray-blue-800)',
            'gray-blue-900': 'var(--gray-blue-900)',
            'gray-blue-950': 'var(--gray-blue-950)',
            'gray-cool-100': 'var(--gray-cool-100)',
            'gray-cool-200': 'var(--gray-cool-200)',
            'gray-cool-25': 'var(--gray-cool-25)',
            'gray-cool-300': 'var(--gray-cool-300)',
            'gray-cool-400': 'var(--gray-cool-400)',
            'gray-cool-50': 'var(--gray-cool-50)',
            'gray-cool-500': 'var(--gray-cool-500)',
            'gray-cool-600': 'var(--gray-cool-600)',
            'gray-cool-700': 'var(--gray-cool-700)',
            'gray-cool-800': 'var(--gray-cool-800)',
            'gray-cool-900': 'var(--gray-cool-900)',
            'gray-cool-950': 'var(--gray-cool-950)',
            'gray-iron-100': 'var(--gray-iron-100)',
            'gray-iron-200': 'var(--gray-iron-200)',
            'gray-iron-25': 'var(--gray-iron-25)',
            'gray-iron-300': 'var(--gray-iron-300)',
            'gray-iron-400': 'var(--gray-iron-400)',
            'gray-iron-50': 'var(--gray-iron-50)',
            'gray-iron-500': 'var(--gray-iron-500)',
            'gray-iron-600': 'var(--gray-iron-600)',
            'gray-iron-700': 'var(--gray-iron-700)',
            'gray-iron-800': 'var(--gray-iron-800)',
            'gray-iron-900': 'var(--gray-iron-900)',
            'gray-iron-950': 'var(--gray-iron-950)',
            'gray-modern-100': 'var(--gray-modern-100)',
            'gray-modern-200': 'var(--gray-modern-200)',
            'gray-modern-25': 'var(--gray-modern-25)',
            'gray-modern-300': 'var(--gray-modern-300)',
            'gray-modern-400': 'var(--gray-modern-400)',
            'gray-modern-50': 'var(--gray-modern-50)',
            'gray-modern-500': 'var(--gray-modern-500)',
            'gray-modern-600': 'var(--gray-modern-600)',
            'gray-modern-700': 'var(--gray-modern-700)',
            'gray-modern-800': 'var(--gray-modern-800)',
            'gray-modern-900': 'var(--gray-modern-900)',
            'gray-modern-950': 'var(--gray-modern-950)',
            'gray-neutral-100': 'var(--gray-neutral-100)',
            'gray-neutral-200': 'var(--gray-neutral-200)',
            'gray-neutral-25': 'var(--gray-neutral-25)',
            'gray-neutral-300': 'var(--gray-neutral-300)',
            'gray-neutral-400': 'var(--gray-neutral-400)',
            'gray-neutral-50': 'var(--gray-neutral-50)',
            'gray-neutral-500': 'var(--gray-neutral-500)',
            'gray-neutral-600': 'var(--gray-neutral-600)',
            'gray-neutral-700': 'var(--gray-neutral-700)',
            'gray-neutral-800': 'var(--gray-neutral-800)',
            'gray-neutral-900': 'var(--gray-neutral-900)',
            'gray-neutral-950': 'var(--gray-neutral-950)',
            'gray-saturate-100': 'var(--gray-saturate-100)',
            'gray-saturate-200': 'var(--gray-saturate-200)',
            'gray-saturate-25': 'var(--gray-saturate-25)',
            'gray-saturate-300': 'var(--gray-saturate-300)',
            'gray-saturate-400': 'var(--gray-saturate-400)',
            'gray-saturate-50': 'var(--gray-saturate-50)',
            'gray-saturate-500': 'var(--gray-saturate-500)',
            'gray-saturate-600': 'var(--gray-saturate-600)',
            'gray-saturate-700': 'var(--gray-saturate-700)',
            'gray-saturate-800': 'var(--gray-saturate-800)',
            'gray-saturate-900': 'var(--gray-saturate-900)',
            'gray-saturate-950': 'var(--gray-saturate-950)',
            'gray-slate-100': 'var(--gray-slate-100)',
            'gray-slate-200': 'var(--gray-slate-200)',
            'gray-slate-25': 'var(--gray-slate-25)',
            'gray-slate-300': 'var(--gray-slate-300)',
            'gray-slate-400': 'var(--gray-slate-400)',
            'gray-slate-50': 'var(--gray-slate-50)',
            'gray-slate-500': 'var(--gray-slate-500)',
            'gray-slate-600': 'var(--gray-slate-600)',
            'gray-slate-700': 'var(--gray-slate-700)',
            'gray-slate-800': 'var(--gray-slate-800)',
            'gray-slate-900': 'var(--gray-slate-900)',
            'gray-slate-950': 'var(--gray-slate-950)',
            'gray-true-100': 'var(--gray-true-100)',
            'gray-true-200': 'var(--gray-true-200)',
            'gray-true-25': 'var(--gray-true-25)',
            'gray-true-300': 'var(--gray-true-300)',
            'gray-true-400': 'var(--gray-true-400)',
            'gray-true-50': 'var(--gray-true-50)',
            'gray-true-500': 'var(--gray-true-500)',
            'gray-true-600': 'var(--gray-true-600)',
            'gray-true-700': 'var(--gray-true-700)',
            'gray-true-800': 'var(--gray-true-800)',
            'gray-true-900': 'var(--gray-true-900)',
            'gray-true-950': 'var(--gray-true-950)',
            'gray-warm-100': 'var(--gray-warm-100)',
            'gray-warm-200': 'var(--gray-warm-200)',
            'gray-warm-25': 'var(--gray-warm-25)',
            'gray-warm-300': 'var(--gray-warm-300)',
            'gray-warm-400': 'var(--gray-warm-400)',
            'gray-warm-50': 'var(--gray-warm-50)',
            'gray-warm-500': 'var(--gray-warm-500)',
            'gray-warm-600': 'var(--gray-warm-600)',
            'gray-warm-700': 'var(--gray-warm-700)',
            'gray-warm-800': 'var(--gray-warm-800)',
            'gray-warm-900': 'var(--gray-warm-900)',
            'gray-warm-950': 'var(--gray-warm-950)',
            'green-100': 'var(--green-100)',
            'green-200': 'var(--green-200)',
            'green-25': 'var(--green-25)',
            'green-300': 'var(--green-300)',
            'green-400': 'var(--green-400)',
            'green-50': 'var(--green-50)',
            'green-500': 'var(--green-500)',
            'green-600': 'var(--green-600)',
            'green-700': 'var(--green-700)',
            'green-800': 'var(--green-800)',
            'green-900': 'var(--green-900)',
            'green-950': 'var(--green-950)',
            'green-light-100': 'var(--green-light-100)',
            'green-light-200': 'var(--green-light-200)',
            'green-light-25': 'var(--green-light-25)',
            'green-light-300': 'var(--green-light-300)',
            'green-light-400': 'var(--green-light-400)',
            'green-light-50': 'var(--green-light-50)',
            'green-light-500': 'var(--green-light-500)',
            'green-light-600': 'var(--green-light-600)',
            'green-light-700': 'var(--green-light-700)',
            'green-light-800': 'var(--green-light-800)',
            'green-light-900': 'var(--green-light-900)',
            'green-light-950': 'var(--green-light-950)',
            'indigo-100': 'var(--indigo-100)',
            'indigo-200': 'var(--indigo-200)',
            'indigo-25': 'var(--indigo-25)',
            'indigo-300': 'var(--indigo-300)',
            'indigo-400': 'var(--indigo-400)',
            'indigo-50': 'var(--indigo-50)',
            'indigo-500': 'var(--indigo-500)',
            'indigo-600': 'var(--indigo-600)',
            'indigo-700': 'var(--indigo-700)',
            'indigo-800': 'var(--indigo-800)',
            'indigo-900': 'var(--indigo-900)',
            'indigo-950': 'var(--indigo-950)',
            'moss-100': 'var(--moss-100)',
            'moss-200': 'var(--moss-200)',
            'moss-25': 'var(--moss-25)',
            'moss-300': 'var(--moss-300)',
            'moss-400': 'var(--moss-400)',
            'moss-50': 'var(--moss-50)',
            'moss-500': 'var(--moss-500)',
            'moss-600': 'var(--moss-600)',
            'moss-700': 'var(--moss-700)',
            'moss-800': 'var(--moss-800)',
            'moss-900': 'var(--moss-900)',
            'moss-950': 'var(--moss-950)',
            'orange-100': 'var(--orange-100)',
            'orange-200': 'var(--orange-200)',
            'orange-25': 'var(--orange-25)',
            'orange-300': 'var(--orange-300)',
            'orange-400': 'var(--orange-400)',
            'orange-50': 'var(--orange-50)',
            'orange-500': 'var(--orange-500)',
            'orange-600': 'var(--orange-600)',
            'orange-700': 'var(--orange-700)',
            'orange-800': 'var(--orange-800)',
            'orange-900': 'var(--orange-900)',
            'orange-950': 'var(--orange-950)',
            'orange-dark-100': 'var(--orange-dark-100)',
            'orange-dark-200': 'var(--orange-dark-200)',
            'orange-dark-25': 'var(--orange-dark-25)',
            'orange-dark-300': 'var(--orange-dark-300)',
            'orange-dark-400': 'var(--orange-dark-400)',
            'orange-dark-50': 'var(--orange-dark-50)',
            'orange-dark-500': 'var(--orange-dark-500)',
            'orange-dark-600': 'var(--orange-dark-600)',
            'orange-dark-700': 'var(--orange-dark-700)',
            'orange-dark-800': 'var(--orange-dark-800)',
            'orange-dark-900': 'var(--orange-dark-900)',
            'orange-dark-950': 'var(--orange-dark-950)',
            'pink-100': 'var(--pink-100)',
            'pink-200': 'var(--pink-200)',
            'pink-25': 'var(--pink-25)',
            'pink-300': 'var(--pink-300)',
            'pink-400': 'var(--pink-400)',
            'pink-50': 'var(--pink-50)',
            'pink-500': 'var(--pink-500)',
            'pink-600': 'var(--pink-600)',
            'pink-700': 'var(--pink-700)',
            'pink-800': 'var(--pink-800)',
            'pink-900': 'var(--pink-900)',
            'pink-950': 'var(--pink-950)',
            'purple-100': 'var(--purple-100)',
            'purple-200': 'var(--purple-200)',
            'purple-25': 'var(--purple-25)',
            'purple-300': 'var(--purple-300)',
            'purple-400': 'var(--purple-400)',
            'purple-50': 'var(--purple-50)',
            'purple-500': 'var(--purple-500)',
            'purple-600': 'var(--purple-600)',
            'purple-700': 'var(--purple-700)',
            'purple-800': 'var(--purple-800)',
            'purple-900': 'var(--purple-900)',
            'purple-950': 'var(--purple-950)',
            'red-100': 'var(--red-100)',
            'red-200': 'var(--red-200)',
            'red-25': 'var(--red-25)',
            'red-300': 'var(--red-300)',
            'red-400': 'var(--red-400)',
            'red-50': 'var(--red-50)',
            'red-500': 'var(--red-500)',
            'red-600': 'var(--red-600)',
            'red-700': 'var(--red-700)',
            'red-800': 'var(--red-800)',
            'red-900': 'var(--red-900)',
            'red-950': 'var(--red-950)',
            'rose-100': 'var(--rose-100)',
            'rose-200': 'var(--rose-200)',
            'rose-25': 'var(--rose-25)',
            'rose-300': 'var(--rose-300)',
            'rose-400': 'var(--rose-400)',
            'rose-50': 'var(--rose-50)',
            'rose-500': 'var(--rose-500)',
            'rose-600': 'var(--rose-600)',
            'rose-700': 'var(--rose-700)',
            'rose-800': 'var(--rose-800)',
            'rose-900': 'var(--rose-900)',
            'rose-950': 'var(--rose-950)',
            'teal-100': 'var(--teal-100)',
            'teal-200': 'var(--teal-200)',
            'teal-25': 'var(--teal-25)',
            'teal-300': 'var(--teal-300)',
            'teal-400': 'var(--teal-400)',
            'teal-50': 'var(--teal-50)',
            'teal-500': 'var(--teal-500)',
            'teal-600': 'var(--teal-600)',
            'teal-700': 'var(--teal-700)',
            'teal-800': 'var(--teal-800)',
            'teal-900': 'var(--teal-900)',
            'teal-950': 'var(--teal-950)',
            'vibrant-yellow-100': 'var(--vibrant-yellow-100)',
            'vibrant-yellow-200': 'var(--vibrant-yellow-200)',
            'vibrant-yellow-25': 'var(--vibrant-yellow-25)',
            'vibrant-yellow-300': 'var(--vibrant-yellow-300)',
            'vibrant-yellow-400': 'var(--vibrant-yellow-400)',
            'vibrant-yellow-50': 'var(--vibrant-yellow-50)',
            'vibrant-yellow-500': 'var(--vibrant-yellow-500)',
            'vibrant-yellow-600': 'var(--vibrant-yellow-600)',
            'vibrant-yellow-700': 'var(--vibrant-yellow-700)',
            'vibrant-yellow-800': 'var(--vibrant-yellow-800)',
            'vibrant-yellow-900': 'var(--vibrant-yellow-900)',
            'vibrant-yellow-950': 'var(--vibrant-yellow-950)',
            'violet-100': 'var(--violet-100)',
            'violet-200': 'var(--violet-200)',
            'violet-25': 'var(--violet-25)',
            'violet-300': 'var(--violet-300)',
            'violet-400': 'var(--violet-400)',
            'violet-50': 'var(--violet-50)',
            'violet-500': 'var(--violet-500)',
            'violet-600': 'var(--violet-600)',
            'violet-700': 'var(--violet-700)',
            'violet-800': 'var(--violet-800)',
            'violet-900': 'var(--violet-900)',
            'violet-950': 'var(--violet-950)',
            'yellow-100': 'var(--yellow-100)',
            'yellow-200': 'var(--yellow-200)',
            'yellow-25': 'var(--yellow-25)',
            'yellow-300': 'var(--yellow-300)',
            'yellow-400': 'var(--yellow-400)',
            'yellow-50': 'var(--yellow-50)',
            'yellow-500': 'var(--yellow-500)',
            'yellow-600': 'var(--yellow-600)',
            'yellow-700': 'var(--yellow-700)',
            'yellow-800': 'var(--yellow-800)',
            'yellow-900': 'var(--yellow-900)',
            'yellow-950': 'var(--yellow-950)',
            'dark-mode-alpha-100': 'var(--dark-mode-alpha-100)',
            'dark-mode-alpha-200': 'var(--dark-mode-alpha-200)',
            'dark-mode-alpha-25': 'var(--dark-mode-alpha-25)',
            'dark-mode-alpha-300': 'var(--dark-mode-alpha-300)',
            'dark-mode-alpha-400': 'var(--dark-mode-alpha-400)',
            'dark-mode-alpha-50': 'var(--dark-mode-alpha-50)',
            'dark-mode-alpha-500': 'var(--dark-mode-alpha-500)',
            'dark-mode-alpha-600': 'var(--dark-mode-alpha-600)',
            'dark-mode-alpha-700': 'var(--dark-mode-alpha-700)',
            'dark-mode-alpha-800': 'var(--dark-mode-alpha-800)',
            'dark-mode-alpha-900': 'var(--dark-mode-alpha-900)',
            'dark-mode-alpha-950': 'var(--dark-mode-alpha-950)',
            'brand-100': 'var(--brand-100)',
            'brand-200': 'var(--brand-200)',
            'brand-25': 'var(--brand-25)',
            'brand-300': 'var(--brand-300)',
            'brand-400': 'var(--brand-400)',
            'brand-50': 'var(--brand-50)',
            'brand-500': 'var(--brand-500)',
            'brand-600': 'var(--brand-600)',
            'brand-700': 'var(--brand-700)',
            'brand-800': 'var(--brand-800)',
            'brand-900': 'var(--brand-900)',
            'brand-950': 'var(--brand-950)',
            'error-100': 'var(--error-100)',
            'error-200': 'var(--error-200)',
            'error-25': 'var(--error-25)',
            'error-300': 'var(--error-300)',
            'error-400': 'var(--error-400)',
            'error-50': 'var(--error-50)',
            'error-500': 'var(--error-500)',
            'error-600': 'var(--error-600)',
            'error-700': 'var(--error-700)',
            'error-800': 'var(--error-800)',
            'error-900': 'var(--error-900)',
            'error-950': 'var(--error-950)',
            'gray-dark-mode-alpha-100': 'var(--gray-dark-mode-alpha-100)',
            'gray-dark-mode-alpha-200': 'var(--gray-dark-mode-alpha-200)',
            'gray-dark-mode-alpha-25': 'var(--gray-dark-mode-alpha-25)',
            'gray-dark-mode-alpha-300': 'var(--gray-dark-mode-alpha-300)',
            'gray-dark-mode-alpha-400': 'var(--gray-dark-mode-alpha-400)',
            'gray-dark-mode-alpha-50': 'var(--gray-dark-mode-alpha-50)',
            'gray-dark-mode-alpha-500': 'var(--gray-dark-mode-alpha-500)',
            'gray-dark-mode-alpha-600': 'var(--gray-dark-mode-alpha-600)',
            'gray-dark-mode-alpha-700': 'var(--gray-dark-mode-alpha-700)',
            'gray-dark-mode-alpha-800': 'var(--gray-dark-mode-alpha-800)',
            'gray-dark-mode-alpha-900': 'var(--gray-dark-mode-alpha-900)',
            'gray-dark-mode-alpha-950': 'var(--gray-dark-mode-alpha-950)',
            'gray-dark-mode-100': 'var(--gray-dark-mode-100)',
            'gray-dark-mode-200': 'var(--gray-dark-mode-200)',
            'gray-dark-mode-25': 'var(--gray-dark-mode-25)',
            'gray-dark-mode-300': 'var(--gray-dark-mode-300)',
            'gray-dark-mode-400': 'var(--gray-dark-mode-400)',
            'gray-dark-mode-50': 'var(--gray-dark-mode-50)',
            'gray-dark-mode-500': 'var(--gray-dark-mode-500)',
            'gray-dark-mode-600': 'var(--gray-dark-mode-600)',
            'gray-dark-mode-700': 'var(--gray-dark-mode-700)',
            'gray-dark-mode-800': 'var(--gray-dark-mode-800)',
            'gray-dark-mode-900': 'var(--gray-dark-mode-900)',
            'gray-dark-mode-950': 'var(--gray-dark-mode-950)',
            'gray-light-mode-100': 'var(--gray-light-mode-100)',
            'gray-light-mode-200': 'var(--gray-light-mode-200)',
            'gray-light-mode-25': 'var(--gray-light-mode-25)',
            'gray-light-mode-300': 'var(--gray-light-mode-300)',
            'gray-light-mode-400': 'var(--gray-light-mode-400)',
            'gray-light-mode-50': 'var(--gray-light-mode-50)',
            'gray-light-mode-500': 'var(--gray-light-mode-500)',
            'gray-light-mode-600': 'var(--gray-light-mode-600)',
            'gray-light-mode-700': 'var(--gray-light-mode-700)',
            'gray-light-mode-800': 'var(--gray-light-mode-800)',
            'gray-light-mode-900': 'var(--gray-light-mode-900)',
            'gray-light-mode-950': 'var(--gray-light-mode-950)',
            'success-100': 'var(--success-100)',
            'success-200': 'var(--success-200)',
            'success-25': 'var(--success-25)',
            'success-300': 'var(--success-300)',
            'success-400': 'var(--success-400)',
            'success-50': 'var(--success-50)',
            'success-500': 'var(--success-500)',
            'success-600': 'var(--success-600)',
            'success-700': 'var(--success-700)',
            'success-800': 'var(--success-800)',
            'success-900': 'var(--success-900)',
            'success-950': 'var(--success-950)',
            'warning-100': 'var(--warning-100)',
            'warning-200': 'var(--warning-200)',
            'warning-25': 'var(--warning-25)',
            'warning-300': 'var(--warning-300)',
            'warning-400': 'var(--warning-400)',
            'warning-50': 'var(--warning-50)',
            'warning-500': 'var(--warning-500)',
            'warning-600': 'var(--warning-600)',
            'warning-700': 'var(--warning-700)',
            'warning-800': 'var(--warning-800)',
            'warning-900': 'var(--warning-900)',
            'warning-950': 'var(--warning-950)'
         },
         _fgColors: {
            'fg-primary-900': 'var(--fg-primary-900)',
            'fg-secondary-700': 'var(--fg-secondary-700)',
            'fg-secondary_hover': 'var(--fg-secondary_hover)',
            'fg-tertiary-600': 'var(--fg-tertiary-600)',
            'fg-tertiary_hover': 'var(--fg-tertiary_hover)',
            'fg-quarterary-500': 'var(--fg-quarterary-500)',
            'fg-quarterary_hover': 'var(--fg-quarterary_hover)',
            'fg-quinary-400': 'var(--fg-quinary-400)',
            'fg-quinary_hover': 'var(--fg-quinary_hover)',
            'fg-senary-300': 'var(--fg-senary-300)',
            'fg-white': 'var(--fg-white)',
            'fg-disabled': 'var(--fg-disabled)',
            'fg-disabled_subtle': 'var(--fg-disabled_subtle)',
            'fg-brand-primary-600': 'var(--fg-brand-primary-600)',
            'fg-brand-primary_alt': 'var(--fg-brand-primary_alt)',
            'fg-brand-secondary-500': 'var(--fg-brand-secondary-500)',
            'fg-error-primary': 'var(--fg-error-primary)',
            'fg-error-secondary': 'var(--fg-error-secondary)',
            'fg-warning-primary': 'var(--fg-warning-primary)',
            'fg-warning-secondary': 'var(--fg-warning-secondary)',
            'fg-success-primary': 'var(--fg-success-primary)',
            'fg-success-secondary': 'var(--fg-success-secondary)'
         },
         _utilityColors: {
            'utility-gray-50': 'var(--utility-gray-50)',
            'utility-gray-100': 'var(--utility-gray-100)',
            'utility-gray-200': 'var(--utility-gray-200)',
            'utility-gray-300': 'var(--utility-gray-300)',
            'utility-gray-400': 'var(--utility-gray-400)',
            'utility-gray-500': 'var(--utility-gray-500)',
            'utility-gray-600': 'var(--utility-gray-600)',
            'utility-gray-700': 'var(--utility-gray-700)',
            'utility-gray-800': 'var(--utility-gray-800)',
            'utility-gray-900': 'var(--utility-gray-900)',
            'utility-gray-warm-50': 'var(--utility-gray-warm-50)',
            'utility-gray-warm-100': 'var(--utility-gray-warm-100)',
            'utility-gray-warm-200': 'var(--utility-gray-warm-200)',
            'utility-gray-warm-300': 'var(--utility-gray-warm-300)',
            'utility-gray-warm-400': 'var(--utility-gray-warm-400)',
            'utility-gray-warm-500': 'var(--utility-gray-warm-500)',
            'utility-gray-warm-600': 'var(--utility-gray-warm-600)',
            'utility-gray-warm-700': 'var(--utility-gray-warm-700)',
            'utility-gray-warm-800': 'var(--utility-gray-warm-800)',
            'utility-gray-warm-900': 'var(--utility-gray-warm-900)',
            'utility-brand-50': 'var(--utility-brand-50)',
            'utility-brand-50_alt': 'var(--utility-brand-50_alt)',
            'utility-brand-100': 'var(--utility-brand-100)',
            'utility-brand-100_alt': 'var(--utility-brand-100_alt)',
            'utility-brand-200': 'var(--utility-brand-200)',
            'utility-brand-200_alt': 'var(--utility-brand-200_alt)',
            'utility-brand-300': 'var(--utility-brand-300)',
            'utility-brand-300_alt': 'var(--utility-brand-300_alt)',
            'utility-brand-400': 'var(--utility-brand-400)',
            'utility-brand-400_alt': 'var(--utility-brand-400_alt)',
            'utility-brand-500': 'var(--utility-brand-500)',
            'utility-brand-500_alt': 'var(--utility-brand-500_alt)',
            'utility-brand-600': 'var(--utility-brand-600)',
            'utility-brand-600_alt': 'var(--utility-brand-600_alt)',
            'utility-brand-700': 'var(--utility-brand-700)',
            'utility-brand-700_alt': 'var(--utility-brand-700_alt)',
            'utility-brand-800': 'var(--utility-brand-800)',
            'utility-brand-800_alt': 'var(--utility-brand-800_alt)',
            'utility-brand-900': 'var(--utility-brand-900)',
            'utility-brand-900_alt': 'var(--utility-brand-900_alt)',
            'utility-error-50': 'var(--utility-error-50)',
            'utility-error-100': 'var(--utility-error-100)',
            'utility-error-200': 'var(--utility-error-200)',
            'utility-error-300': 'var(--utility-error-300)',
            'utility-error-400': 'var(--utility-error-400)',
            'utility-error-500': 'var(--utility-error-500)',
            'utility-error-600': 'var(--utility-error-600)',
            'utility-error-700': 'var(--utility-error-700)',
            'utility-warning-50': 'var(--utility-warning-50)',
            'utility-warning-100': 'var(--utility-warning-100)',
            'utility-warning-200': 'var(--utility-warning-200)',
            'utility-warning-300': 'var(--utility-warning-300)',
            'utility-warning-400': 'var(--utility-warning-400)',
            'utility-warning-500': 'var(--utility-warning-500)',
            'utility-warning-600': 'var(--utility-warning-600)',
            'utility-warning-700': 'var(--utility-warning-700)',
            'utility-success-50': 'var(--utility-success-50)',
            'utility-success-100': 'var(--utility-success-100)',
            'utility-success-200': 'var(--utility-success-200)',
            'utility-success-300': 'var(--utility-success-300)',
            'utility-success-400': 'var(--utility-success-400)',
            'utility-success-500': 'var(--utility-success-500)',
            'utility-success-600': 'var(--utility-success-600)',
            'utility-success-700': 'var(--utility-success-700)',
            'utility-gray-blue-50': 'var(--utility-gray-blue-50)',
            'utility-gray-blue-100': 'var(--utility-gray-blue-100)',
            'utility-gray-blue-200': 'var(--utility-gray-blue-200)',
            'utility-gray-blue-300': 'var(--utility-gray-blue-300)',
            'utility-gray-blue-400': 'var(--utility-gray-blue-400)',
            'utility-gray-blue-500': 'var(--utility-gray-blue-500)',
            'utility-gray-blue-600': 'var(--utility-gray-blue-600)',
            'utility-gray-blue-700': 'var(--utility-gray-blue-700)',
            'utility-gray-blue-800': 'var(--utility-gray-blue-800)',
            'utility-gray-blue-900': 'var(--utility-gray-blue-900)',
            'utility-moss-50': 'var(--utility-moss-50)',
            'utility-moss-100': 'var(--utility-moss-100)',
            'utility-moss-200': 'var(--utility-moss-200)',
            'utility-moss-300': 'var(--utility-moss-300)',
            'utility-moss-400': 'var(--utility-moss-400)',
            'utility-moss-500': 'var(--utility-moss-500)',
            'utility-moss-600': 'var(--utility-moss-600)',
            'utility-moss-700': 'var(--utility-moss-700)',
            'utility-moss-800': 'var(--utility-moss-800)',
            'utility-moss-900': 'var(--utility-moss-900)',
            'utility-green-light-50': 'var(--utility-green-light-50)',
            'utility-green-light-100': 'var(--utility-green-light-100)',
            'utility-green-light-200': 'var(--utility-green-light-200)',
            'utility-green-light-300': 'var(--utility-green-light-300)',
            'utility-green-light-400': 'var(--utility-green-light-400)',
            'utility-green-light-500': 'var(--utility-green-light-500)',
            'utility-green-light-600': 'var(--utility-green-light-600)',
            'utility-green-light-700': 'var(--utility-green-light-700)',
            'utility-green-light-800': 'var(--utility-green-light-800)',
            'utility-green-light-900': 'var(--utility-green-light-900)',
            'utility-teal-50': 'var(--utility-teal-50)',
            'utility-teal-100': 'var(--utility-teal-100)',
            'utility-teal-200': 'var(--utility-teal-200)',
            'utility-teal-300': 'var(--utility-teal-300)',
            'utility-teal-400': 'var(--utility-teal-400)',
            'utility-teal-500': 'var(--utility-teal-500)',
            'utility-teal-600': 'var(--utility-teal-600)',
            'utility-teal-700': 'var(--utility-teal-700)',
            'utility-teal-800': 'var(--utility-teal-800)',
            'utility-teal-900': 'var(--utility-teal-900)',
            'utility-cyan-50': 'var(--utility-cyan-50)',
            'utility-cyan-100': 'var(--utility-cyan-100)',
            'utility-cyan-200': 'var(--utility-cyan-200)',
            'utility-cyan-300': 'var(--utility-cyan-300)',
            'utility-cyan-400': 'var(--utility-cyan-400)',
            'utility-cyan-500': 'var(--utility-cyan-500)',
            'utility-cyan-600': 'var(--utility-cyan-600)',
            'utility-cyan-700': 'var(--utility-cyan-700)',
            'utility-cyan-800': 'var(--utility-cyan-800)',
            'utility-cyan-900': 'var(--utility-cyan-900)',
            'utility-blue-light-50': 'var(--utility-blue-light-50)',
            'utility-blue-light-100': 'var(--utility-blue-light-100)',
            'utility-blue-light-200': 'var(--utility-blue-light-200)',
            'utility-blue-light-300': 'var(--utility-blue-light-300)',
            'utility-blue-light-400': 'var(--utility-blue-light-400)',
            'utility-blue-light-500': 'var(--utility-blue-light-500)',
            'utility-blue-light-600': 'var(--utility-blue-light-600)',
            'utility-blue-light-700': 'var(--utility-blue-light-700)',
            'utility-blue-light-800': 'var(--utility-blue-light-800)',
            'utility-blue-light-900': 'var(--utility-blue-light-900)',
            'utility-blue-50': 'var(--utility-blue-50)',
            'utility-blue-100': 'var(--utility-blue-100)',
            'utility-blue-200': 'var(--utility-blue-200)',
            'utility-blue-300': 'var(--utility-blue-300)',
            'utility-blue-400': 'var(--utility-blue-400)',
            'utility-blue-500': 'var(--utility-blue-500)',
            'utility-blue-600': 'var(--utility-blue-600)',
            'utility-blue-700': 'var(--utility-blue-700)',
            'utility-blue-800': 'var(--utility-blue-800)',
            'utility-blue-900': 'var(--utility-blue-900)',
            'utility-blue-dark-50': 'var(--utility-blue-dark-50)',
            'utility-blue-dark-100': 'var(--utility-blue-dark-100)',
            'utility-blue-dark-200': 'var(--utility-blue-dark-200)',
            'utility-blue-dark-300': 'var(--utility-blue-dark-300)',
            'utility-blue-dark-400': 'var(--utility-blue-dark-400)',
            'utility-blue-dark-500': 'var(--utility-blue-dark-500)',
            'utility-blue-dark-600': 'var(--utility-blue-dark-600)',
            'utility-blue-dark-700': 'var(--utility-blue-dark-700)',
            'utility-blue-dark-800': 'var(--utility-blue-dark-800)',
            'utility-blue-dark-900': 'var(--utility-blue-dark-900)',
            'utility-indigo-50': 'var(--utility-indigo-50)',
            'utility-indigo-100': 'var(--utility-indigo-100)',
            'utility-indigo-200': 'var(--utility-indigo-200)',
            'utility-indigo-300': 'var(--utility-indigo-300)',
            'utility-indigo-400': 'var(--utility-indigo-400)',
            'utility-indigo-500': 'var(--utility-indigo-500)',
            'utility-indigo-600': 'var(--utility-indigo-600)',
            'utility-indigo-700': 'var(--utility-indigo-700)',
            'utility-indigo-800': 'var(--utility-indigo-800)',
            'utility-indigo-900': 'var(--utility-indigo-900)',
            'utility-violet-50': 'var(--utility-violet-50)',
            'utility-violet-100': 'var(--utility-violet-100)',
            'utility-violet-200': 'var(--utility-violet-200)',
            'utility-violet-300': 'var(--utility-violet-300)',
            'utility-violet-400': 'var(--utility-violet-400)',
            'utility-violet-500': 'var(--utility-violet-500)',
            'utility-violet-600': 'var(--utility-violet-600)',
            'utility-violet-700': 'var(--utility-violet-700)',
            'utility-violet-800': 'var(--utility-violet-800)',
            'utility-violet-900': 'var(--utility-violet-900)',
            'utility-purple-50': 'var(--utility-purple-50)',
            'utility-purple-100': 'var(--utility-purple-100)',
            'utility-purple-200': 'var(--utility-purple-200)',
            'utility-purple-300': 'var(--utility-purple-300)',
            'utility-purple-400': 'var(--utility-purple-400)',
            'utility-purple-500': 'var(--utility-purple-500)',
            'utility-purple-600': 'var(--utility-purple-600)',
            'utility-purple-700': 'var(--utility-purple-700)',
            'utility-purple-800': 'var(--utility-purple-800)',
            'utility-purple-900': 'var(--utility-purple-900)',
            'utility-fuchsia-50': 'var(--utility-fuchsia-50)',
            'utility-fuchsia-100': 'var(--utility-fuchsia-100)',
            'utility-fuchsia-200': 'var(--utility-fuchsia-200)',
            'utility-fuchsia-300': 'var(--utility-fuchsia-300)',
            'utility-fuchsia-400': 'var(--utility-fuchsia-400)',
            'utility-fuchsia-500': 'var(--utility-fuchsia-500)',
            'utility-fuchsia-600': 'var(--utility-fuchsia-600)',
            'utility-fuchsia-700': 'var(--utility-fuchsia-700)',
            'utility-fuchsia-800': 'var(--utility-fuchsia-800)',
            'utility-fuchsia-900': 'var(--utility-fuchsia-900)',
            'utility-pink-50': 'var(--utility-pink-50)',
            'utility-pink-100': 'var(--utility-pink-100)',
            'utility-pink-200': 'var(--utility-pink-200)',
            'utility-pink-300': 'var(--utility-pink-300)',
            'utility-pink-400': 'var(--utility-pink-400)',
            'utility-pink-500': 'var(--utility-pink-500)',
            'utility-pink-600': 'var(--utility-pink-600)',
            'utility-pink-700': 'var(--utility-pink-700)',
            'utility-pink-800': 'var(--utility-pink-800)',
            'utility-pink-900': 'var(--utility-pink-900)',
            'utility-rose-50': 'var(--utility-rose-50)',
            'utility-rose-100': 'var(--utility-rose-100)',
            'utility-rose-200': 'var(--utility-rose-200)',
            'utility-rose-300': 'var(--utility-rose-300)',
            'utility-rose-400': 'var(--utility-rose-400)',
            'utility-rose-500': 'var(--utility-rose-500)',
            'utility-rose-600': 'var(--utility-rose-600)',
            'utility-rose-700': 'var(--utility-rose-700)',
            'utility-rose-800': 'var(--utility-rose-800)',
            'utility-rose-900': 'var(--utility-rose-900)',
            'utility-orange-dark-50': 'var(--utility-orange-dark-50)',
            'utility-orange-dark-100': 'var(--utility-orange-dark-100)',
            'utility-orange-dark-200': 'var(--utility-orange-dark-200)',
            'utility-orange-dark-300': 'var(--utility-orange-dark-300)',
            'utility-orange-dark-400': 'var(--utility-orange-dark-400)',
            'utility-orange-dark-500': 'var(--utility-orange-dark-500)',
            'utility-orange-dark-600': 'var(--utility-orange-dark-600)',
            'utility-orange-dark-700': 'var(--utility-orange-dark-700)',
            'utility-orange-dark-800': 'var(--utility-orange-dark-800)',
            'utility-orange-dark-900': 'var(--utility-orange-dark-900)',
            'utility-orange-50': 'var(--utility-orange-50)',
            'utility-orange-100': 'var(--utility-orange-100)',
            'utility-orange-200': 'var(--utility-orange-200)',
            'utility-orange-300': 'var(--utility-orange-300)',
            'utility-orange-400': 'var(--utility-orange-400)',
            'utility-orange-500': 'var(--utility-orange-500)',
            'utility-orange-600': 'var(--utility-orange-600)',
            'utility-orange-700': 'var(--utility-orange-700)',
            'utility-orange-800': 'var(--utility-orange-800)',
            'utility-orange-900': 'var(--utility-orange-900)',
            'utility-yellow-50': 'var(--utility-yellow-50)',
            'utility-yellow-100': 'var(--utility-yellow-100)',
            'utility-yellow-200': 'var(--utility-yellow-200)',
            'utility-yellow-300': 'var(--utility-yellow-300)',
            'utility-yellow-400': 'var(--utility-yellow-400)',
            'utility-yellow-500': 'var(--utility-yellow-500)',
            'utility-yellow-600': 'var(--utility-yellow-600)',
            'utility-yellow-700': 'var(--utility-yellow-700)',
            'utility-yellow-800': 'var(--utility-yellow-800)',
            'utility-yellow-900': 'var(--utility-yellow-900)'
         },
         _componentColors: {
            'nav-item-button-icon-fg': 'var(--nav-item-button-icon-fg)',
            'nav-item-button-icon-fg_active':
               'var(--nav-item-button-icon-fg_active)',
            'nav-item-icon-fg': 'var(--nav-item-icon-fg)',
            'nav-item-dark-icon-fg': 'var(--nav-item-dark-icon-fg)',
            'nav-item-icon-fg_active': 'var(--nav-item-icon-fg_active)',
            'breadcrumb-fg': 'var(--breadcrumb-fg)',
            'breadcrumb-fg_hover': 'var(--breadcrumb-fg_hover)',
            'breadcrumb-brand-fg_hover': 'var(--breadcrumb-brand-fg_hover)',
            'breadcrumb-icon-fg': 'var(--breadcrumb-icon-fg)',
            'breadcrumb-icon-fg_hover': 'var(--breadcrumb-icon-fg_hover)',
            'breadcrumb-brand-icon-fg_hover':
               'var(--breadcrumb-brand-icon-fg_hover)',
            'button-primary-fg': 'var(--button-primary-fg)',
            'button-primary-fg_hover': 'var(--button-primary-fg_hover)',
            'button-secondary-fg': 'var(--button-secondary-fg)',
            'button-secondary-fg_hover': 'var(--button-secondary-fg_hover)',
            'button-secondary-color-fg': 'var(--button-secondary-color-fg)',
            'button-secondary-color-fg_hover':
               'var(--button-secondary-color-fg_hover)',
            'button-tertiary-fg': 'var(--button-tertiary-fg)',
            'button-tertiary-fg_hover': 'var(--button-tertiary-fg_hover)',
            'button-tertiary-color-fg': 'var(--button-tertiary-color-fg)',
            'button-tertiary-color-fg_hover':
               'var(--button-tertiary-color-fg_hover)',
            'button-primary-error-fg': 'var(--button-primary-error-fg)',
            'button-primary-error-fg_hover':
               'var(--button-primary-error-fg_hover)',
            'button-secondary-error-fg': 'var(--button-secondary-error-fg)',
            'button-secondary-error-fg_hover':
               'var(--button-secondary-error-fg_hover)',
            'button-tertiary-error-fg': 'var(--button-tertiary-error-fg)',
            'button-tertiary-error-fg_hover':
               'var(--button-tertiary-error-fg_hover)',
            'footer-button-fg': 'var(--footer-button-fg)',
            'footer-button-fg_hover': 'var(--footer-button-fg_hover)',
            'footer-badge-fg': 'var(--footer-badge-fg)',
            'icon-fg-brand': 'var(--icon-fg-brand)',
            'icon-fg-brand_on-brand': 'var(--icon-fg-brand_on-brand)',
            'icon-fg': 'var(--icon-fg)',
            'featured-icon-light-fg-brand':
               'var(--featured-icon-light-fg-brand)',
            'featured-icon-light-fg-gray': 'var(--featured-icon-light-fg-gray)',
            'featured-icon-light-fg-error':
               'var(--featured-icon-light-fg-error)',
            'featured-icon-light-fg-warning':
               'var(--featured-icon-light-fg-warning)',
            'featured-icon-light-fg-success':
               'var(--featured-icon-light-fg-success)',
            'featured-icon-dark-fg-brand': 'var(--featured-icon-dark-fg-brand)',
            'featured-icon-dark-fg-gray': 'var(--featured-icon-dark-fg-gray)',
            'featured-icon-dark-fg-error': 'var(--featured-icon-dark-fg-error)',
            'featured-icon-dark-fg-warning':
               'var(--featured-icon-dark-fg-warning)',
            'featured-icon-dark-fg-success':
               'var(--featured-icon-dark-fg-success)',
            'social-icon-fg-x': 'var(--social-icon-fg-x)',
            'social-icon-fg-instagram': 'var(--social-icon-fg-instagram)',
            'social-icon-fg-apple': 'var(--social-icon-fg-apple)',
            'social-icon-fg-github': 'var(--social-icon-fg-github)',
            'social-icon-fg-angellist': 'var(--social-icon-fg-angellist)',
            'social-icon-fg-tumblr': 'var(--social-icon-fg-tumblr)',
            'thumbnail-badge-brand-fg': 'var(--thumbnail-badge-brand-fg)',
            'thumbnail-badge-success-fg': 'var(--thumbnail-badge-success-fg)',
            'toggle-button-fg_disabled': 'var(--toggle-button-fg_disabled)',
            'wysiwyg-editor-icon-fg': 'var(--wysiwyg-editor-icon-fg)',
            'wysiwyg-editor-icon-fg_active':
               'var(--wysiwyg-editor-icon-fg_active)'
         },
         colors: ({ theme }) => ({
            ...theme('_fgColors'),
            ...theme('_utilityColors'),
            ...theme('_baseColors'),
            ...theme('_componentColors')
         }),

         backgroundColor: ({ theme }) => ({
            ...theme('colors'),

            primary: 'var(--bg-primary)',
            'primary-dark': 'var(--bg-primary-dark)',
            primary_alt: 'var(--bg-primary_alt)',
            primary_hover: 'var(--bg-primary_hover)',
            'primary-dark_hover': 'var(--bg-primary-dark_hover)',
            'primary-subtle': 'var(--bg-primary-subtle)',
            'primary-solid': 'var(--bg-primary-solid)',
            secondary: 'var(--bg-secondary)',
            secondary_alt: 'var(--bg-secondary_alt)',
            secondary_hover: 'var(--bg-secondary_hover)',
            secondary_subtle: 'var(--bg-secondary_subtle)',
            'secondary-solid': 'var(--bg-secondary-solid)',
            tertiary: 'var(--bg-tertiary)',
            quaternary: 'var(--bg-quaternary)',
            active: 'var(--bg-active)',
            disabled: 'var(--bg-disabled)',
            disabled_subtle: 'var(--bg-disabled_subtle)',
            overlay: 'var(--bg-overlay)',
            'brand-primary': 'var(--bg-brand-primary)',
            'brand-primary_hover': 'var(--bg-brand-primary_hover)',
            'brand-primary_alt': 'var(--bg-brand-primary_alt)',
            'brand-primary-dark_alt': 'var(--bg-brand-primary-dark_alt)',
            'brand-secondary': 'var(--bg-brand-secondary)',
            'brand-secondary_hover': 'var(--bg-brand-secondary_hover)',
            'brand-solid': 'var(--bg-brand-solid)',
            'brand-solid_hover': 'var(--bg-brand-solid_hover)',
            'brand-section': 'var(--bg-brand-section)',
            'brand-section_subtle': 'var(--bg-brand-section_subtle)',
            'error-primary': 'var(--bg-error-primary)',
            'error-secondary': 'var(--bg-error-secondary)',
            'error-solid': 'var(--bg-error-solid)',
            'error-solid_hover': 'var(--bg-error-solid_hover)',
            'warning-primary': 'var(--bg-warning-primary)',
            'warning-secondary': 'var(--bg-warning-secondary)',
            'warning-solid': 'var(--bg-warning-solid)',
            'success-primary': 'var(--bg-success-primary)',
            'success-secondary': 'var(--bg-success-secondary)',
            'success-solid': 'var(--bg-success-solid)'
         }),
         borderColor: ({ theme }) => ({
            ...theme('colors'),

            primary: 'var(--border-primary)',
            hover: 'var(--border-hover)',
            secondary: 'var(--border-secondary)',
            dark: 'var(--border-dark)',
            tertiary: 'var(--border-tertiary)',
            disabled: 'var(--border-disabled)',
            disabled_subtle: 'var(--border-disabled_subtle)',
            brand: 'var(--border-brand)',
            'brand-solid': 'var(--border-brand-solid)',
            'brand-solid_alt': 'var(--border-brand-solid_alt)',
            error: 'var(--border-error)',
            'error-solid': 'var(--border-error-solid)',
            success: 'var(--border-success)',
            'success-solid': 'var(--border-success-solid)',
            warning: 'var(--border-warning)',
            'warning-solid': 'var(--border-warning-solid)'
         }),
         textColor: ({ theme }) => ({
            ...theme('colors'),

            'primary-900': 'var(--text-primary-900)',
            'primary_on-brand': 'var(--text-primary_on-brand)',
            'secondary-700': 'var(--text-secondary-700)',
            'secondary-dark-200': 'var(--text-secondary-dark-200)',
            secondary_hover: 'var(--text-secondary_hover)',
            'secondary_on-brand': 'var(--text-secondary_on-brand)',
            'tertiary-600': 'var(--text-tertiary-600)',
            tertiary_hover: 'var(--text-tertiary_hover)',
            'tertiary_on-brand': 'var(--text-tertiary_on-brand)',
            'quarterary-500': 'var(--text-quarterary-500)',
            'quarterary_on-brand': 'var(--text-quarterary_on-brand)',
            white: 'var(--text-white)',
            disabled: 'var(--text-disabled)',
            placeholder: 'var(--text-placeholder)',
            placeholder_subtle: 'var(--text-placeholder_subtle)',
            'brand-primary-900': 'var(--text-brand-primary-900)',
            'brand-secondary-700': 'var(--text-brand-secondary-700)',
            'brand-tertiary-600': 'var(--text-brand-tertiary-600)',
            'brand-tertiary_alt': 'var(--text-brand-tertiary_alt)',
            'error-primary-600': 'var(--text-error-primary-600)',
            'warning-primary-600': 'var(--text-warning-primary-600)',
            'success-primary-600': 'var(--text-success-primary-600)'
         }),

         borderRadius: {
            none: '0px',
            xxs: '2px',
            xs: '4px',
            sm: '6px',
            md: '8px',
            lg: '10px',
            xl: '12px',
            '2xl': '16px',
            '3xl': '20px',
            '4xl': '24px',
            full: '9999px'
         },
         borderWidth: {
            1: '1px'
         },

         spacing: {
            0: '0px',
            0.5: '2px',
            1: '4px',
            1.5: '6px',
            2: '8px',
            2.5: '10px',
            3: '12px',
            3.5: '14px',
            4: '16px',
            4.5: '18px',
            5: '20px',
            5.5: '22px',
            6: '24px',
            8: '32px',
            10: '40px',
            12: '48px',
            16: '64px',
            20: '80px',
            24: '96px',
            32: '128px',
            40: '160px',
            48: '192px',
            56: '224px',
            64: '256px',
            80: '320px',
            96: '384px',
            120: '480px',
            140: '560px',
            160: '640px',
            180: '720px',
            192: '768px',
            256: '1024px',
            320: '1280px',
            360: '1440px',
            400: '1600px',
            480: '1920px',
            none: '0px',
            xxs: '2px',
            xs: '4px',
            sm: '6px',
            md: '8px',
            'md-utility': '10px',
            lg: '12px',
            'lg-utility': '14px',
            xl: '16px',
            'xl-utility': '18px',
            '2xl': '20px',
            '2xl-utility': '22px',
            '3xl': '24px',
            '4xl': '32px',
            '5xl': '40px',
            '6xl': '48px',
            '7xl': '64px',
            '8xl': '80px',
            '9xl': '96px',
            '10xl': '128px',
            '11xl': '160px'
         },

         gap: ({ theme }) => theme('spacing'),
         margin: ({ theme }) => ({
            ...theme('spacing'),
            auto: 'auto'
         }),
         padding: ({ theme }) => ({
            ...theme('spacing'),
            'xxs_border-1': `calc(${theme('spacing.xxs')} - ${theme(
               'borderWidth.1'
            )})`,
            'xs_border-1': `calc(${theme('spacing.xs')} - ${theme(
               'borderWidth.1'
            )})`,
            'sm_border-1': `calc(${theme('spacing.sm')} - ${theme(
               'borderWidth.1'
            )})`,
            'md_border-1': `calc(${theme('spacing.md')} - ${theme(
               'borderWidth.1'
            )})`,
            'lg_border-1': `calc(${theme('spacing.lg')} - ${theme(
               'borderWidth.1'
            )})`,
            'xl_border-1': `calc(${theme('spacing.xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '2xl_border-1': `calc(${theme('spacing.2xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '3xl_border-1': `calc(${theme('spacing.3xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '4xl_border-1': `calc(${theme('spacing.4xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '5xl_border-1': `calc(${theme('spacing.5xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '6xl_border-1': `calc(${theme('spacing.6xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '7xl_border-1': `calc(${theme('spacing.7xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '8xl_border-1': `calc(${theme('spacing.8xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '9xl_border-1': `calc(${theme('spacing.9xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '10xl_border-1': `calc(${theme('spacing.10xl')} - ${theme(
               'borderWidth.1'
            )})`,
            '11xl_border-1': `calc(${theme('spacing.11xl')} - ${theme(
               'borderWidth.1'
            )})`
         }),

         width: ({ theme }) => ({
            xxs: theme('spacing.80'),
            xs: theme('spacing.96'),
            sm: theme('spacing.120'),
            md: theme('spacing.140'),
            lg: theme('spacing.160'),
            xl: theme('spacing.192'),
            '2xl': theme('spacing.256'),
            '3xl': theme('spacing.320'),
            '4xl': theme('spacing.360'),
            '5xl': theme('spacing.400'),
            '6xl': theme('spacing.480'),
            'paragraph-max-width': theme('spacing.180')
         })
      }
   },

   plugins: [
      plugin(function ({ addComponents, theme }) {
         addComponents({
            '.app-store-badge-border': {
               borderColor: 'var(--app-store-badge-border)'
            },
            '.nav-item-text_active': { color: 'var(--nav-item-text_active)' },
            '.avatar-bg': { backgroundColor: 'var(--avatar-bg)' },
            '.avatar-profile-photo-border': {
               borderColor: 'var(--avatar-profile-photo-border)'
            },
            '.avatar-contrast-border': {
               borderColor: 'var(--avatar-contrast-border)'
            },
            '.avatar-focus-border': {
               borderColor: 'var(--avatar-focus-border)'
            },
            '.breadcrumb-bg_hover': {
               backgroundColor: 'var(--breadcrumb-bg_hover)'
            },
            '.breadcrumb-brand-bg_hover': {
               backgroundColor: 'var(--breadcrumb-brand-bg_hover)'
            },
            '.button-primary-bg': {
               backgroundColor: 'var(--button-primary-bg)'
            },
            '.button-primary-bg_hover': {
               backgroundColor: 'var(--button-primary-bg_hover)'
            },
            '.button-primary-border': {
               borderColor: 'var(--button-primary-border)'
            },
            '.button-primary-border_hover': {
               borderColor: 'var(--button-primary-border_hover)'
            },
            '.button-secondary-bg': {
               backgroundColor: 'var(--button-secondary-bg)'
            },
            '.button-secondary-bg_hover': {
               backgroundColor: 'var(--button-secondary-bg_hover)'
            },
            '.button-secondary-border': {
               borderColor: 'var(--button-secondary-border)'
            },
            '.button-secondary-border_hover': {
               borderColor: 'var(--button-secondary-border_hover)'
            },
            '.button-secondary-color-bg': {
               backgroundColor: 'var(--button-secondary-color-bg)'
            },
            '.button-secondary-color-bg_hover': {
               backgroundColor: 'var(--button-secondary-color-bg_hover)'
            },
            '.button-secondary-color-border': {
               borderColor: 'var(--button-secondary-color-border)'
            },
            '.button-secondary-color-border_hover': {
               borderColor: 'var(--button-secondary-color-border_hover)'
            },
            '.button-tertiary-bg_hover': {
               backgroundColor: 'var(--button-tertiary-bg_hover)'
            },
            '.button-tertiary-color-bg_hover': {
               backgroundColor: 'var(--button-tertiary-color-bg_hover)'
            },
            '.button-primary-error-bg': {
               backgroundColor: 'var(--button-primary-error-bg)'
            },
            '.button-primary-error-bg_hover': {
               backgroundColor: 'var(--button-primary-error-bg_hover)'
            },
            '.button-primary-error-border': {
               borderColor: 'var(--button-primary-error-border)'
            },
            '.button-primary-error-border_hover': {
               borderColor: 'var(--button-primary-error-border_hover)'
            },
            '.button-secondary-error-bg': {
               backgroundColor: 'var(--button-secondary-error-bg)'
            },
            '.button-secondary-error-bg_hover': {
               backgroundColor: 'var(--button-secondary-error-bg_hover)'
            },
            '.button-secondary-error-border': {
               borderColor: 'var(--button-secondary-error-border)'
            },
            '.button-secondary-error-border_hover': {
               borderColor: 'var(--button-secondary-error-border_hover)'
            },
            '.button-tertiary-error-bg_hover': {
               backgroundColor: 'var(--button-tertiary-error-bg_hover)'
            },
            '.footer-badge-bg': { backgroundColor: 'var(--footer-badge-bg)' },
            '.footer-badge-border': {
               borderColor: 'var(--footer-badge-border)'
            },
            '.header-abstract-50-bg': {
               backgroundColor: 'var(--header-abstract-50-bg)'
            },
            '.header-abstract-100-bg': {
               backgroundColor: 'var(--header-abstract-100-bg)'
            },
            '.header-abstract-200-bg': {
               backgroundColor: 'var(--header-abstract-200-bg)'
            },
            '.header-abstract-300-bg': {
               backgroundColor: 'var(--header-abstract-300-bg)'
            },
            '.featured-icon-modern-border': {
               borderColor: 'var(--featured-icon-modern-border)'
            },
            '.screen-mockup-border': {
               borderColor: 'var(--screen-mockup-border)'
            },
            '.slider-handle-bg': { backgroundColor: 'var(--slider-handle-bg)' },
            '.slider-handle-border': {
               borderColor: 'var(--slider-handle-border)'
            },
            '.tooltip-supporting-text': {
               color: 'var(--tooltip-supporting-text)'
            }
         })
      })
   ]
}
